activemq:
  producer:
    broker:
      url: tcp://localhost:61616
      username: admin
  consumer:
    brokers:
      - broker:
        url: tcp://localhost:61616
        username: admin
      - broker:
        url: tcp://localhost:61616
        username: admin